name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            pm2 stop backend
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ed25519
            cd ~/him-backend
            git stash
            git pull
            git status
            git checkout master
            npm install
            npm run build
            pm2 restart backend
